routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\VisimisiController;
use App\Http\Controllers\pengelolaprodiController;
use App\Http\Controllers\KerjasamapendidikanController;
use App\Http\Controllers\KerjasamapenelitianController;
use App\Http\Controllers\KerjasamapkmController;
use App\Http\Controllers\SeleksimhsbaruController;
use App\Http\Controllers\MhsasingController;
use App\Http\Controllers\DosentetapptController;
use App\Http\Controllers\DosbingtaController;
use App\Http\Controllers\EwmpController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile');
Route::resource('pengguna', PenggunaController::class);
Route::resource('mahasiswa', MahasiswaController::class);
Route::resource('visimisi', VisimisiController::class);
Route::resource('pengelolaprodi', pengelolaprodiController::class);
Route::resource('Kerjasamapendidikan', KerjasamapendidikanController::class);
Route::resource('Kerjasamapenelitian', KerjasamapenelitianController::class);
Route::resource('Kerjasamapkm', KerjasamapkmController::class);
Route::resource('Seleksimhsbaru', SeleksimhsbaruController::class);
Route::resource('Mhsasing', MhsasingController::class);
Route::resource('Dosentetappt', DosentetapptController::class);
Route::resource('Dosbingta', DosbingtaController::class);
Route::resource('Ewmp', EwmpController::class);

app/Models/Visimisi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Visimisi extends Model
{
    use HasFactory;
    Protected $table = 'vmts';
    Protected $fillable = ['id','visimisi'];
    Public $timestamps = false;
}

app/Http/Controllers/VisimisiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Visimisi;

class VisimisiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $visimisi = Visimisi::latest()->paginate(10);

        return view('visimisi.index',compact('visimisi'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('visimisi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'visimisi'=> 'required',
 

        ]);

        Visimisi::create($request->all());
        return redirect()->route('visimisi.index')
                        ->with('berhasil','datadisimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Visimisi $visimisi)
    {
        return view('visimisi.show', compact('visimisi'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Visimisi $visimisi)
    {
        return view ('visimisi.edit', compact('visimisi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Visimisi $visimisi)
    {
        $request-> validate([
            'visimisi'=> 'required',


        ]);

        $visimisi->update($request->all());

        return redirect()->route('visimisi.index')
                        ->with('berhasil','data sudah datadisimpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Visimisi $visimisi)
    {
        $visimisi->delete();
        return redirect()->route('visimisi.index')
                        ->with('berhasil','data sudah dihapus');
    }
}

resources/views/visimisi/create.blade.php
@extends('adminlte::page')

@section('content')
 <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Data Mahasiswa Test</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Test data mahasiswa </li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">


@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Wadooo</strong> Ada masalah dalam inputan.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

            
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Data Mahasiswa </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('mahasiswa.store') }}" method="POST">
                   @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="nama">Nama Mahasiswa</label>
                    <input type="text" class="form-control" id="nama" name="nama" placeholder="masukan nama">
                  </div>
                  <div class="form-group">
                    <label for="nim">Nomor Induk Mahasiswa</label>
                    <input type="text" class="form-control" id="nim" name="nim" placeholder="masukan nim">
                  </div>
                  <div class="form-group">
                      <label for="prodi">Program Studi</label>
                    <input type="text" class="form-control" id="prodi" name="prodi" placeholder="program studi">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
              
      
@endsection

resources/views/visimisi/edit.blade.php
 @extends('adminlte::page')

@section('content')
 <!-- Content Header (Page header) -->
  <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
          
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Tambah Visi dan Misi</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">

   <script src="https://cdn.tiny.cloud/1/qly7ft1kwgvykr6rvvnfqbgya7orou7ji03skp7zgxblivtw/tinymce/5/tinymce.min.js" referrerpolicy="origin">
 </script>
<div class="container">
  <div class="row">
    <div class="col-md-12">
    <form action="{{ route('visimisi.store') }}" method="POST">
            @csrf
        <textarea id="visimisi" name="visimisi" rows="12" cols="6">
          
          {{ $visimisi->visimisi }}

        </textarea>
           <div class="form-group" >
                            <div class="col-md-12 col-md-offset-6 text-right" style="margin-top:20px">
                                <button type="submit" class="col-md-2 btn btn-primary"  >Simpan</button>
                                <button type="button" class="col-md-2 btn btn-danger" style="margin-left:10px" onclick="window.location='{{ url('/visimisi') }}'" >Kembali</button>
                            </div>
                        </div>
      </form>
          
   
      
    </div>
  </div>
  

</div>
<script>
  tinymce.init({
      selector: 'textarea',
      plugins: 'a11ychecker advcode casechange formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
      toolbar: 'a11ycheck addcomment showcomments casechange checklist code formatpainter pageembed permanentpen table',
      toolbar_mode: 'floating',
      tinycomments_mode: 'embedded',
      tinycomments_author: 'Author name',
   });
  </script>
     </div>
        <!-- /.card-body -->
        <div class="card-footer">
          SimPati PeDe 2020 @muhamad irfan setiawan - STMIK SUMEDANG 
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
     @endsection

resources/views/visimisi/index.blade.php
 @extends('adminlte::page')

@section('content')
 <!-- Content Header (Page header) -->
  <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Mahasiswa</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="home">Home</a></li>
              <li class="breadcrumb-item active">Mahasiswa</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Data Mahasiswa</h3>
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>                                                
        <div class="card-body">
          <!-- Tombol untuk menampilkan modal-->
            <button type="button" class="btn btn-primary btn" data-toggle="modal" data-target="#modalTambahmhs">Tambah</button>
           
            <!-- Modal -->

            <div class="modal fade" id="modalTambahmhs" tabindex="-1" aria-labelledby="modalTambahmhs" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                          <h5 class="modal-title">Tambah Data Mahasiswa</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                    </div>
                    <div class="modal-body">
                    <!--FORM TAMBAH BARANG-->
                          <form action="{{ route('mahasiswa.store') }}" method="POST">
                            @csrf
                                  <div class="form-group">
                                    <label for="">Nama</label>
                                    <input type="text" class="form-control" id="nama" name="nama" aria-describedby="emailHelp">
                                    </div>
                                  <div class="form-group">
                                      <label for="">NIM</label>
                                      <input type="text" class="form-control" id="nim" name="nim">
                                  </div>
                                  <div class="form-group">
                                      <label for="">Program Studi</label>
                                      <input type="text" class="form-control" id="prodi" name="prodi">
                                  </div>
                          <button type="submit" class="btn btn-primary">Simpan Data</button>
                          </form>
                    <!--END FORM TAMBAH BARANG-->
                    </div>
                    </div>
                  </div>
                </div>

            
        </div>


    <div class="card-body">

    <table class="table table-bordered">
        <tr>
            <th width="20px" class="text-center">No</th>
            <th width="280px" class="text-center">Nama</th>
            <th width="280px" class="text-center">NIM</th>
            <th width="280px" class="text-center">Program Studi</th>
            <th width="200px"class="text-center">Action</th>
        </tr>
        @foreach ($mahasiswa as $v)
        <tr>
            <td width="20px" class="text-center">{{ ++$i }}</td>
            <td width="280x">{{ $v->nama }}</div></td>
            <td width="280px">{{ $v->nim }}</div></td>
            <td width="280px">{{ $v->prodi }}</div></td>
            <td width="100px">


                  <!--modal Show-->
                  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalshowmhs1{{ $v->id_mhs }}">Detail</button>
                  <div class="modal fade" id="modalshowmhs1{{ $v->id_mhs }}" tabindex="-1" aria-labelledby="modalTambahmhs1" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                                <h5 class="modal-title">Detail Data Mahasiswa</h5>
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                      </button>
                          </div>
                          <div class="modal-body">
                              <table class="table">
                                <tbody>
                                  <tr>
                                      <td>Nama</td>
                                      <td width="5px">:</td>
                                      <td>{{ $v->nama }}</td>
                                    </tr>
                                    <tr>
                                      <td>Nomor Induk Mahasiswa</td>
                                      <td width="5px">:</td>
                                      <td>{{ $v->nim }}</td>
                                    </tr>
                                    <tr>
                                      <td>Program Studi</td>
                                      <td width="5px">:</td>
                                      <td>{{ $v->prodi }}</td>
                                  </tr>
                                </tbody>
                              </table>
                            <div class="modal-footer justify-content-between">
                              <button type="button" class="btn btn-primary" data-dismiss="modal">Kembali</button>
                              <!--button type="button" class="btn btn-primary">Save changes</button-->
                            </div>
                          </div>
                        </div>
                      </div>

                      </div>


                  <!--modal hapus-->
                  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalTambahmhs{{ $v->id_mhs }}">Edit</button>
                  <div class="modal fade" id="modalTambahmhs{{ $v->id_mhs }}" tabindex="-1" aria-labelledby="modalTambahmhs1" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                                <h5 class="modal-title">Edit Data Mahasiswa</h5>
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                      </button>
                          </div>
                          <div class="modal-body">
                                <form action="{{ route('mahasiswa.update',$v->id_mhs) }}" method="POST">
                                  @csrf
                                  @method('put')
                                        <div class="form-group">
                                          <label for="">Nama</label>
                                          <input type="text" class="form-control" id="nama" name="nama" aria-describedby="emailHelp" value="{{ $v->nama }}">
                                          </div>
                                        <div class="form-group">
                                            <label for="">NIM</label>
                                            <input type="text" class="form-control" id="nim" name="nim" value="{{ $v->nim }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="">Program Studi</label>
                                            <select name="prodi" id="prodi" class="form-control">
                                              <option value="">Pilh Program Studi</option>
                                              <option value="Teknik Informatika">Teknik Informatika</option>
                                              <option value="Sistem Informasi">Sistem Informasi</option>
                                              <option value="Manajemen Informatika">Manajemen Informatika</option>
                                            </select>
                                        </div>
                                <button type="submit" class="btn btn-primary">Simpan Data</button>
                                </form>
                      
                          </div>
                          </div>
                        </div>
                      </div>
                    
                    <!--modal hapus-->
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalHapusMHS{{ $v->id_mhs }}">Delete</button>
                    <div class="modal fade" id="modalHapusMHS{{ $v->id_mhs }}" tabindex="-1" aria-labelledby="modalHapusMHS" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-body">
                                  <h4 class="text-center">Apakah anda yakin menghapus Data ini? :</h4>
                                  </div>
                                  <div class="modal-footer">
                                    <form action="{{ route('mahasiswa.destroy',$v->id_mhs) }}" method="POST">
                                      @csrf
                                      @method('DELETE')
                                      <button type="submit" class="btn btn-primary">Hapus Data!</button>
                                    </form>
                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
                            </div>
                          </div>
                        </div>
                    </div>

                      
                  
                  
          
            </td>
        </tr>
        @endforeach
    </table>

     </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
   @stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

resources/views/visimisi/show.blade.php
@extends('adminlte::page')

@section('content')

<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Mahasiswa</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="home">Home</a></li>
              <li class="breadcrumb-item active">Mahasiswa</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Data Mahasiswa</h3>
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>                                                
        <div class="card-body">
      	

     
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>



@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop