routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\VisimisiController;
use App\Http\Controllers\pengelolaprodiController;
use App\Http\Controllers\KerjasamapendidikanController;
use App\Http\Controllers\KerjasamapenelitianController;
use App\Http\Controllers\KerjasamapkmController;
use App\Http\Controllers\SeleksimhsbaruController;
use App\Http\Controllers\MhsasingController;
use App\Http\Controllers\DosentetapptController;
use App\Http\Controllers\DosbingtaController;
use App\Http\Controllers\EwmpController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile');
Route::resource('pengguna', PenggunaController::class);
Route::resource('mahasiswa', MahasiswaController::class);
Route::resource('visimisi', VisimisiController::class);
Route::resource('pengelolaprodi', pengelolaprodiController::class);
Route::resource('Kerjasamapendidikan', KerjasamapendidikanController::class);
Route::resource('Kerjasamapenelitian', KerjasamapenelitianController::class);
Route::resource('Kerjasamapkm', KerjasamapkmController::class);
Route::resource('Seleksimhsbaru', SeleksimhsbaruController::class);
Route::resource('Mhsasing', MhsasingController::class);
Route::resource('Dosentetappt', DosentetapptController::class);
Route::resource('Dosbingta', DosbingtaController::class);
Route::resource('Ewmp', EwmpController::class);

app/Models/Kerjasamapendidikan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kerjasamapendidikan extends Model
{
    use HasFactory;
    protected $table = 'kerjasama_pendidikan';
	protected $primaryKey = 'id_kerjasamapendidikan';
	protected $fillable = [

	'id_kerjasamapendidikan',
	'lembaga_mitra',
	'tingkat',
	'judul_kegiatan_kerja',
	'manfaat',
	'waktu_durasi',
	'bukti_kerjasama',
	'tahun_berakhir_kjsm'
	];  
	public $timestamps = false;  
}

app/Http/Controllers/KerjasamapendidikanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kerjasamapendidikan;

class KerjasamapendidikanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Kerjasamapendidikan = Kerjasamapendidikan::latest()->paginate(10);

        return view('Kerjasamapendidikan.index',compact('Kerjasamapendidikan'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Kerjasamapendidikan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           'lembaga_mitra' => 'required',
           'judul_kegiatan_kerja' => 'required',
           'tingkat' => 'required',
           'manfaat' => 'required',
           'waktu_durasi' => 'required',
           'bukti_kerjasama' => 'required',
           'tahun_berakhir_kjsm' => 'required'
        ]);

        Kerjasamapendidikan::create($request->all());
        return redirect()->route('Kerjasamapendidikan.index')
                        ->with('berhasil','datadisimpan');
    }

    /**
     * Display the specified resource.
     *
     \Illuminate\Http\Response
     */
    public function show($id_kerjasamapendidikan)
    {
        $Kerjasamapendidikan=Kerjasamapendidikan::find($id_kerjasamapendidikan);
        return view('Kerjasamapendidikan.show', compact('Kerjasamapendidikan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     \Illuminate\Http\Response
     */
    public function edit($id_kerjasamapendidikan)
    {
        $Kerjasamapendidikan=Kerjasamapendidikan::find($id_kerjasamapendidikan);
        return view ('Kerjasamapendidikan.edit', compact('Kerjasamapendidikan'));
    }

    /**
     * Update the specified resource in storage.
     *

     */
    public function update(Request $request, $id_kerjasamapendidikan)
    {
        $request -> validate([
           'lembaga_mitra' => 'required',
           'judul_kegiatan_kerja' => 'required',
           'tingkat' => 'required',
           'manfaat' => 'required',
           'waktu_durasi' => 'required',
           'bukti_kerjasama' => 'required',
           'tahun_berakhir_kjsm' => 'required'
        ]);

        $Kerjasamapendidikan=Kerjasamapendidikan::find($id_kerjasamapendidikan)->update($request->all());

        return redirect()->route('Kerjasamapendidikan.index')
                        ->with('berhasil','data sudah dirubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     \Illuminate\Http\Response
     */
    public function destroy($id_kerjasamapendidikan)
    {
        $Kerjasamapendidikan=Kerjasamapendidikan::find($id_kerjasamapendidikan)->delete();
        return redirect()->route('Kerjasamapendidikan.index')
                        ->with('berhasil','data sudah dihapus');
    }
}

resources/views/Kerjasamapendidikan/create.blade.php
@extends('adminlte::page')

@section('content')
 <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Data PS</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Test data mahasiswa </li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">


@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Wadooo</strong> Ada masalah dalam inputan.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

            
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Data ps </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
             <form action="{{ route('Daftarpsunipengelolaps.store') }}" method="POST">
                            @csrf
                                  <div class="form-group">
                                    <label for="">Jenis Program</label>
                                    <input type="text" class="form-control" id="jenis_program" name="jenis_program" aria-describedby="emailHelp">
                                    </div>
                                  <div class="form-group">
                                      <label for="">Nama Program Studi</label>
                                      <input type="text" class="form-control" id="nama_ps" name="nama_ps">
                                  </div>
                                  <div class="form-group">
                                      <label for="">Status</label>
                                      <input type="text" class="form-control" id="status" name="status">
                                  </div>
                                     <div class="form-group">
                                      <label for="">No. Tanggal SK</label>
                                      <input type="text" class="form-control" id="no_tgl_sk" name="no_tgl_sk">
                                  </div>
                                     <div class="form-group">
                                      <label for="">Tanggal Kadaluarsa</label>
                                      <input type="text" class="form-control" id="tgl_kadaluarsa" name="tgl_kadaluarsa">
                                  </div>   
                                  <div class="form-group">
                                      <label for="">Jumlah Mahasiswa Saat TS</label>
                                      <input type="text" class="form-control" id="jml_mhs_saat_ts" name="jml_mhs_saat_ts">
                                  </div>
                                  
                          <button type="submit" class="btn btn-primary">Simpan Data</button>
                          </form>
            </div>
              
      
@endsection

resources/views/Kerjasamapendidikan/edit.blade.php
@extends('adminlte::page')


@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Edit Pegawai</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-secondary" href="{{ route('pengelolaprodi.index') }}"> Kembali</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Muup ea</strong> Ada yg gak beres nginputna.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
 <div class="body">
                    <!--FORM TAMBAH PS-->
        <form action="{{ route('pengelolaprodi.update', $d->id) }}" method="POST">
            
        @csrf
        @method('PUT')

         <div class="form-group">
                                    <label for="">Jenis Program</label>
                                    <input type="text" class="form-control" id="jenis_program" name="jenis_program" value="{{$d->jenis_program}}">
                                    </div>
                                  <div class="form-group">
                                      <label for="">Nama Program Studi</label>
                                      <input type="text" class="form-control" id="nama_ps" name="nama_ps" value="{{ $d->nama_ps }}">
                                  </div>
                                  <div class="form-group">
                                      <label for="">Status</label>
                                      <input type="text" class="form-control" id="status" name="status" value="{{$d->status}}">
                                  </div>
                                     <div class="form-group">
                                      <label for="">No. Tanggal SK</label>
                                      <input type="text" class="form-control" id="no_tgl_sk" name="no_tgl_sk" value="{{$d->no_tgl_sk }}">
                                  </div>
                                     <div class="form-group">
                                      <label for="">Tanggal Kadaluarsa</label>
                                      <input type="text" class="form-control" id="tgl_kadaluarsa" name="tgl_kadaluarsa" value="{{ $d->tgl_kadaluarsa }}">
                                  </div>   
                                  <div class="form-group">
                                      <label for="">Jumlah Mahasiswa Saat TS</label>
                                      <input type="text" class="form-control" id="jml_mhs_saat_ts" name="jml_mhs_saat_ts" value="{{ $d->jml_mhs_saat_ts }}">
                                  </div>
                                  
                          <button type="submit" class="btn btn-primary">Simpan Data</button>
                          </form>
          
          
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>

    </form>
                    <!--END FORM TAMBAH BARANG-->
                    </div>
@endsection

resources/views/Kerjasamapendidikan/index.blade.php
@extends('adminlte::page')

@section('content')
 <!-- Content Header (Page header) -->
  <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Kerjasama Pendidikan</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="home">Home</a></li>
              <li class="breadcrumb-item active">Kerjasama Pendidikan</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Kerjasama Pendidikan</h3>
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>                                                
        <div class="card-body">

                  @if ($errors->any())
                      <div class="alert alert-danger">
                          <strong>Whoops!</strong> There were some problems with your input.<br><br>
                          <ul>
                              @foreach ($errors->all() as $error)
                                  <li>{{ $error }}</li>
                              @endforeach
                          </ul>
                      </div>
                  @endif
          <!-- Tombol untuk menampilkan modal-->
            <button type="button" class="btn btn-primary btn" data-toggle="modal" data-target="#modalEdit">Tambah</button>
           
            <!-- Modal -->

            <div class="modal fade" id="modalEdit" tabindex="-1" aria-labelledby="modalEdit" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                          <h5 class="modal-title">Tambah Kerjasama Pendidikan</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                    </div>
                    <div class="modal-body">
                    <!--FORM TAMBAH PS-->
                          <form action="{{ route('Kerjasamapendidikan.store') }}" method="POST">
                            @csrf
                                  <div class="form-group">
                                    <label for="">Lembaga Mitra</label>
                                    <input type="text" class="form-control" id="lembaga_mitra" name="lembaga_mitra" aria-describedby="emailHelp">
                                    </div>
                                 <div class="form-group">
                                      <label for="">tingkat</label>
                                      <select name="tingkat" id="tingkat" class="form-control">
                                        <option value="Internasional">Internasional</option>
                                        <option value="Nasional">Nasional</option>
                                        <option value="Wilayah/Lokal">Wilayah dan Lokal</option>
                                      </select>

                                  </div>
                             
                                   <div class="form-group">
                                    <label for="">judul kegiatan kerjasama </label>
                                    <input type="text" class="form-control" id="judul_kegiatan_kerja" name="judul_kegiatan_kerja" aria-describedby="emailHelp">
                                    </div>

                                     <div class="form-group">
                                    <label for="">Manfaat </label>
                                    <input type="text" class="form-control" id="manfaat" name="manfaat" aria-describedby="emailHelp">
                                    </div>

                                  <div class="form-group">
                                      <label for="">Waktu dan Durasi</label>
                                      <input type="text" class="form-control" id="waktu_durasi" name="waktu_durasi">
                                  </div>
                                  <div class="form-group">
                                      <label for="">Bukti Kerjasama</label>
                                      <input type="text" class="form-control" id="bukti_kerjasama" name="bukti_kerjasama">
                                  </div>
                                    <div class="form-group">
                                      <label for="">Tahun Berakhir</label>
                                      <input type="text" class="form-control" id="tahun_berakhir_kjsm" name="tahun_berakhir_kjsm">
                                  </div>
                          <button type="submit" class="btn btn-primary">Simpan Data</button>
                          </form>
                    <!--END FORM TAMBAH BARANG-->
                    </div>
                    </div>
                  </div>
                </div>

            
        </div>


    <div class="card-body">

    <table class="table table-bordered">
        <tr>

            <th width="20px" class="text-center">Lembaga Mitra</th>
            <th width="280px" class="text-center">Tingkat</th>
            <th width="280px" class="text-center">Judul</th>
            <th width="280px" class="text-center">Manfaat</th>
            <th width="280px" class="text-center">Waktu</th>
            <th width="280px" class="text-center">Bukti Kerjasama</th>
            <th width="280px" class="text-center">Tahun berakhir</th>
            <th width="200px"class="text-center">Action</th>
        </tr>
        @foreach ($Kerjasamapendidikan as $item)
        <tr>
 
            <td width="280x">{{ $item->lembaga_mitra }}</div></td>
            <td width="280px">{{ $item->tingkat }}</div></td>
            <td width="280px">{{ $item->judul_kegiatan_kerja }}</div></td>
            <td width="280px">{{ $item->manfaat }}</div></td>
            <td width="280px">{{ $item->waktu_durasi }}</div></td>
            <td width="280px">{{ $item->bukti_kerjasama }}</div></td>
            <td width="280px">{{ $item->tahun_berakhir_kjsm }}</div></td>
            <td width="100px">

              <!--modal edit -->
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalEdit{{ $item->id_kerjasamapendidikan }}">Edit</button>
                <div class="modal fade" id="modalEdit{{ $item->id_kerjasamapendidikan }}" tabindex="-1" aria-labelledby="modalEdit1" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                          <h5 class="modal-title">Edit Data Kerjasama </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                    </div>
                    <div class="modal-body">
                    <!--FORM TAMBAH PS-->
            
                                <form action="{{ route('Kerjasamapendidikan.update', $item->id_kerjasamapendidikan) }}" method="POST">
            
                                @csrf
                                @method('PUT')

                                 @if ($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>
                                @endif

                                 <div class="form-group">
                                    <label for="">Lembaga Mitra</label>
                                    <input type="text" class="form-control" id="lembaga_mitra" name="lembaga_mitra" aria-describedby="emailHelp" value="{{$item->lembaga_mitra}}">
                                    </div>
                                  <div class="form-group">
                                      <label for="">tingkat</label>
                                      <select name="tingkat" id="tingkat" class="form-control">
                                        <option value="Internasional">Internasional</option>
                                        <option value="Nasional">Nasional</option>
                                        <option value="Wilayah/Lokal">Wilayah dan Lokal</option>
                                      </select>

                                  </div>
                             
                                   <div class="form-group">
                                    <label for="">judul kegiatan kerjasama </label>
                                    <input type="text" class="form-control" id="judul_kegiatan_kerja" name="judul_kegiatan_kerja" aria-describedby="emailHelp" value="{{$item->judul_kegiatan_kerja}}">
                                    </div>

                                     <div class="form-group">
                                    <label for="">Manfaat </label>
                                    <input type="text" class="form-control" id="manfaat" name="manfaat" aria-describedby="emailHelp" value="{{$item->manfaat}}">
                                    </div>

                                  <div class="form-group">
                                      <label for="">Waktu dan Durasi</label>
                                      <input type="text" class="form-control" id="waktu_durasi" name="waktu_durasi" value="{{$item->waktu_durasi}}">
                                  </div>
                                  <div class="form-group">
                                      <label for="">Bukti Kerjasama</label>
                                      <input type="text" class="form-control" id="bukti_kerjasama" name="bukti_kerjasama" value="{{$item->bukti_kerjasama}}">
                                  </div>
                                    <div class="form-group">
                                      <label for="">Tahun Berakhir</label>
                                      <input type="text" class="form-control" id="tahun_berakhir_kjsm" name="tahun_berakhir_kjsm" value="{{$item->tahun_berakhir_kjsm}}">
                                  </div>
                                  
                          <button type="submit" class="btn btn-primary">Simpan Data</button>
                          </form>
                    <!--END FORM TAMBAH BARANG-->
                    </div>
                    </div>
                  </div>
                </div>

                    

                    <form action="{{ route('Kerjasamapendidikan.destroy',$item->id_kerjasamapendidikan) }}" method="POST">
                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                </form>

          
            </td>
        </tr>
        @endforeach
    </table>
     </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
   @stop